# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-04-21 23:27
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('teacherapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='classroom',
            name='students',
            field=models.ManyToManyField(related_name='classes', to='teacherapp.Student'),
        ),
    ]
