# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-04-22 01:47
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('teacherapp', '0002_auto_20160421_2327'),
    ]

    operations = [
        migrations.RenameField(
            model_name='student',
            old_name='lasr_name',
            new_name='last_name',
        ),
    ]
