# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-04-23 22:52
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('teacherapp', '0003_auto_20160422_0147'),
    ]

    operations = [
        migrations.AlterField(
            model_name='classroom',
            name='subject_title',
            field=models.CharField(max_length=64),
        ),
        migrations.AlterField(
            model_name='student',
            name='first_name',
            field=models.CharField(max_length=30),
        ),
        migrations.AlterField(
            model_name='student',
            name='last_name',
            field=models.CharField(max_length=30),
        ),
    ]
